version: '3'
services:
  client:
    image: 'liambarrett1986/multi-client'
    mem_limit: 128m
    hostname: client
  api:
    image: 'liambarrett1986/multi-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_HOST=$PG_HOST
      - PG_PORT=$PG_PORT
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
      - PG_DATABASE=$PG_DATABASE
  engine:
    image: 'liambarrett1986/multi-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'liambarrett1986/multi-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
    depends_on:
      - api
      - client
    restart: always