name: Deploy MultiDocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test
 
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client ./client
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx ./nginx
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-server ./server
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker
