name: Build
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/react-test npm test
 
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client ./client
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx ./nginx
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-server ./server
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker

      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-client
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-server
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Fibonacci Calculator
          environment_name: Fibonaccicalculator-env
          existing_bucket_name: elasticbeanstalk-eu-west-1-137923721777
          region: eu-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip